version: '3.8'

services:
  keycloak:
    build: .
    container_name: auth-service-provider
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password

      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true 
      
      - KC_FEATURES=token-exchange

      - KC_HOSTNAME=localhost

    ports:
      - "8080:8080"  
      - "8443:8443"  
      - "9000:9000"  

    volumes:
      - keycloak_data:/opt/keycloak/data  
    networks:
      - keycloak_network

    depends_on:
      - postgres  

    command: ["start-dev"]  #  For production: ["start", "--optimized", "--hostname=localhost"]

  postgres:
    image: postgres:17.2
    # postgres:alpine3.20
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network

volumes:
  keycloak_data:
  postgres_data:

networks:
  keycloak_network:
    driver: bridge
